### ISSUE TITLE
Remove embedded Vector source

### ISSUE THREAD

**Issue by ddiss** [performancecopilot/pcp-webjs#3]
pcp-webjs currently includes an out of date copy of Netflix Vector (v1.1.2 is released upstream). Doing so is confusing for downstream packaging, as it's unclear which version should be shipped. E.g. the upstream Fedora spec file includes the following logic:
<pre>
# prefer latest released Netflix version over pcp-webjs copy.
rm -fr pcp-webjs/vector
sed -i -e 's/vector [0-9]\.[0-9]*\.[0-9]*/vector/g' pcp-webjs/index.html
mv pcp-webjs/* $RPM_BUILD_ROOT/%{_datadir}/pcp/webapps
rmdir pcp-webjs
mv vector $RPM_BUILD_ROOT/%{_datadir}/pcp/webapps
</pre>

My preference would be to remove the duplicate Vector source from pcp-webjs, or at least replace it with a git submodule link instead.

**Comment by fche** [comment]
FWIW I don't see signs of _confusion_ - that script knows exactly what it's doing.
The pcp-webjs copy is one that we (I) have personally tested & qualified to work, that is all.
Can you offer a theory of harm of the status quo?

**Comment by ddiss** [comment]
Well hopefully I can be counted as a sign of confusion - I'm attempting to package Vector (alongside webjs) for openSUSE, and had no idea which Vector source to package until I came across the Fedora spec file magic.

IMO an upstream or downstream spec file would offer a more suitable reference for tested / qualified versions, or a git submodule link in pcp-webjs.

**Comment by fche** [comment]
There is no possible git-submodule that I am aware of that links to a -deployable- (built) copy of vector, only its sources.  If you look closely at the fedora spec file, it replaces pcp-webjs' copy of vector 1.1.0 with its own copy of vector 1.1.0.

**Comment by ddiss** [comment]
Oh okay, I wasn't aware that Vector went through a build process before being copied and committed to pcp-webjs.
Still, my confusion behind the reason for the duplicate sources still stands. If you'd prefer to keep it as is, then feel free to ignore this report.

**Comment by fche** [comment]
I'm trying to build & update pcp-webjs to 1.1.2 as we speak.  A great many javascript library prereqs.  Onward!

**Comment by fche** [comment]
Done.

**Comment by fche** [comment]
(To clarify, I updated the pcp-webjs upstream git repo at git://sourceware.org/git/pcpfans.git branch webjs .  I no longer (?!) have access to this github repo to update it myself.)

**Comment by natoscott** [comment]
+1 from me to change in this area @ddiss - it's clearly confusing (maybe not to @fche but certainly to everyone else)

In a perfect world, pcp-webjs would not exist at all.  It would be much cleaner to have independent trees for each of the upstream builds (Vector, Graphite, Grafana).  Ideally, we would build these from source as part of the package build, and not embed pre-built versions - they use different frameworks, have different upstreams, and are logically separate entities - it's not good that we treat them like binary blobs at packaging time.

| [...] we (I) have personally tested

Can you expand on who you think "we" is here please @fche?  It's certainly not anyone working on packaging and maintaining PCP (cos we're as confused as @ddiss) nor anyone working on Vector AFAICT.

It remains a complete mystery why you refuse to collaborate and test Vector alongside the Vector developers, before each Vector release, instead of only afterward when you duplicate it into pcp-webjs some months/years later.

| There is no possible git-submodule that I am aware of that links to a -deployable- (built) copy of vector, only its sources.

OK, let's make a deployable Vector repo - that's a good initial step toward resolving this on-going confusion.

**Comment by natoscott** [comment]
| I no longer (?!) have access to this github repo to update it myself.)

The github web interface is saying you do have write access - what's the error you're seeing?

I did notice that 2FA appears to be disabled on your account now, whereas previously that wasn't the case ... have you changed something at your end?  Can you write to any of your other github repos currently?

**Comment by ddiss** [comment]
Thanks for the feedback, Nathan.

> OK, let's make a deployable Vector repo - that's a good initial step toward resolving this on-going confusion.

That'd be great. I'd like to help with this where I can.
I'll hold off on packaging Vector (and Graphite + Grafana) for openSUSE at this stage.

**Comment by natoscott** [comment]
OK, thanks @ddiss - I'll look into this shortly, pcp-webjs was only meant to be a temporary solution when I created the repo originally and it has evidently reached its use-by-date.

The goals will be to remove the spec file hacks, and have clear source/repo versioning so we don't get into the uncertain states Lukas, myself and now you have seen when doing packaging.

**Comment by fche** [comment]
pcp-webjs is exactly a repo for deployable webapps.  That is why it exists: they are ready-to-run, tested, compatible.  Partitioning it into sibling git repos rather than sibling directories seems like make-work, but to each his own.

**Comment by natoscott** [comment]
Glad to hear you're on board @fche 

For those of us involved with the packaging side of things it'll be a useful step forward.

**Comment by fche** [comment]
I wouldn't say "on board" - rather "try it if you like".  pcp-webjs will continue to fulfil its present function until a superior solution appears.

**Comment by natoscott** [comment]
@ddiss I've pushed a rework of this area of the build in now for pcp-3.11.9 - hopefully this helps you out too with your rebuild.

It's alot clearer and easier to see what's going on now, there's no special spec file hacks for individual webapps anymore, and we have better version tracking of each webapp.  Enjoy!
